"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { Check, Edit3, ExternalLink, Plus, RefreshCw, Search, Trash2 } from "lucide-react";

type Project={id:string;name:string;event_type:string|null;status:string;event_date:string|null;city:string|null};
type Props={resource:"tasks"|"milestones"|"budget"|"suppliers"|"team"|"guests"|"files"|"messages"|"activity";title:string;eyebrow:string;description:string};

const initial:any={title:"",description:"",category:"",status:"pending",due_date:"",sort_order:0,milestone_date:"",milestone_time:"",planned_amount:"",approved_amount:"",paid_amount:"",approval:"pending",supplier_id:"",notes:"",name:"",contact_name:"",email:"",phone:"",role:"",plus_ones:0,storage_key:"",mime_type:"",size_bytes:"",body:""};

function money(v:any){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:2}).format(Number(v)||0)}
function date(v:any){return v?new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(String(v).slice(0,10)+"T12:00:00")).replace(".","").toUpperCase():"A DEFINIR"}

export default function OperationalModule({resource,title,eyebrow,description}:Props){
 const [projects,setProjects]=useState<Project[]>([]),[projectId,setProjectId]=useState(""),[items,setItems]=useState<any[]>([]),[form,setForm]=useState<any>(initial),[editing,setEditing]=useState<string|null>(null),[showForm,setShowForm]=useState(false),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const loadProjects=async()=>{const r=await fetch("/api/admin/projects",{cache:"no-store"});const b=await r.json();if(r.ok){setProjects(b.projects||[]);if(!projectId&&b.projects?.[0])setProjectId(b.projects[0].id)}};
 const loadItems=async(id=projectId)=>{if(resource==="activity"&&!id){setLoading(true)};setLoading(true);const url="/api/admin/workspace?resource="+resource+(id?"&project_id="+encodeURIComponent(id):"");const r=await fetch(url,{cache:"no-store"});const b=await r.json();if(r.ok)setItems(b.items||[]);else setError(b.error||"Não foi possível carregar os dados.");setLoading(false)};
 useEffect(()=>{loadProjects().catch(()=>setError("Não foi possível carregar os projetos."))},[]);
 useEffect(()=>{if(resource==="activity"){loadItems(projectId).catch(()=>setError("Não foi possível carregar a atividade."));return} if(projectId)loadItems(projectId).catch(()=>setError("Não foi possível carregar os registros."))},[resource,projectId]);
 const projectName=useMemo(()=>projects.find(p=>p.id===projectId)?.name||"Todos os projetos", [projects,projectId]);
 const filtered=items.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));
 const reset=()=>{setForm(initial);setEditing(null);setShowForm(false);setError(null)};
 const save=async(e:FormEvent)=>{e.preventDefault();setError(null);setSaving(true);try{const payload={...form,resource,project_id:projectId,id:editing};const r=await fetch("/api/admin/workspace",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const b=await r.json();if(!r.ok)throw new Error(b.error||"Não foi possível salvar.");await loadItems();reset()}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar.")}finally{setSaving(false)}};
 const remove=async(id:string)=>{if(!window.confirm("Excluir este registro?"))return;const r=await fetch("/api/admin/workspace",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,id})});const b=await r.json();if(!r.ok){setError(b.error||"Não foi possível excluir.");return}setItems(v=>v.filter(x=>x.id!==id))};
 const edit=(item:any)=>{setEditing(item.id);setForm({...initial,...item});setShowForm(true);setError(null)};
 const input=(label:string,key:string,type="text",extra:any={})=><label>{label}<input type={type} value={form[key]??""} onChange={e=>setForm((v:any)=>({...v,[key]:e.target.value}))} {...extra}/></label>;
 const select=(label:string,key:string,options:[string,string][])=> <label>{label}<select value={form[key]??""} onChange={e=>setForm((v:any)=>({...v,[key]:e.target.value}))}>{options.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>;
 const renderForm=()=>resource==="tasks"?<>{input("Título *","title")}<div className="adminFormTwo">{select("Status","status",[["pending","Pendente"],["in_progress","Em andamento"],["completed","Concluída"],["cancelled","Cancelada"]])}{input("Prazo","due_date","date")}</div><div className="adminFormTwo">{input("Categoria","category")}{input("Ordem","sort_order","number")}</div>{input("Descrição","description")}</>
 :resource==="milestones"?<>{input("Marco *","title")}<div className="adminFormTwo">{input("Data *","milestone_date","date")}{input("Horário","milestone_time","time")}</div>{input("Descrição","description")}</>
 :resource==="budget"?<>{input("Descrição *","description")}<div className="adminFormTwo">{input("Categoria","category")}{select("Aprovação","approval",[["pending","Pendente"],["approved","Aprovado"],["rejected","Reprovado"]])}</div><div className="adminFormTwo">{input("Planejado","planned_amount","number",{min:0,step:"0.01"})}{input("Aprovado","approved_amount","number",{min:0,step:"0.01"})}</div>{input("Pago","paid_amount","number",{min:0,step:"0.01"})}{input("Observações","notes")}</>
 :resource==="suppliers"?<>{input("Fornecedor *","name")}<div className="adminFormTwo">{input("Categoria","category")}{select("Status","status",[["Cotação","Cotação"],["Negociação","Negociação"],["Contratado","Contratado"],["Concluído","Concluído"]])}</div>{input("Contato","contact_name")}<div className="adminFormTwo">{input("E-mail","email","email")}{input("Telefone","phone")}</div>{input("Observações","notes")}</>
 :resource==="team"?<>{input("Nome *","name")}<div className="adminFormTwo">{input("Função","role")}{input("Telefone","phone")}</div>{input("E-mail","email","email")}{input("Observações","notes")}</>
 :resource==="guests"?<>{input("Nome *","name")}<div className="adminFormTwo">{input("E-mail","email","email")}{input("Telefone","phone")}</div><div className="adminFormTwo">{select("Status","status",[["pending","Pendente"],["confirmed","Confirmado"],["declined","Recusou"],["maybe","Talvez"]])}{input("+1s","plus_ones","number",{min:0})}</div>{input("Observações","notes")}</>
 :resource==="files"?<>{input("Nome do arquivo *","name")}<label>Link / chave privada do arquivo<input value={form.storage_key??""} onChange={e=>setForm((v:any)=>({...v,storage_key:e.target.value}))} placeholder="https://... ou chave do storage"/></label><div className="adminFormTwo">{input("Categoria","category")}{input("Tipo MIME","mime_type")}</div>{input("Tamanho (bytes)","size_bytes","number")}</>
 :<>{<label>Mensagem *<textarea value={form.body??""} onChange={e=>setForm((v:any)=>({...v,body:e.target.value}))} placeholder="Escreva uma atualização para o projeto."/></label>}</>;
 const renderItem=(x:any)=>{if(resource==="tasks")return <><b>{x.title}</b><small>{x.category||"Produção"} · {x.status==="completed"?"Concluída":x.status==="in_progress"?"Em andamento":"Pendente"}{x.due_date?" · "+date(x.due_date):""}</small></>;if(resource==="milestones")return <><b>{x.title}</b><small>{date(x.milestone_date)}{x.milestone_time?" · "+String(x.milestone_time).slice(0,5):""}</small></>;if(resource==="budget")return <><b>{x.description}</b><small>{x.category||"Custo"} · Planejado {money(x.planned_amount)} · Aprovado {money(x.approved_amount)} · Pago {money(x.paid_amount)}</small></>;if(resource==="suppliers")return <><b>{x.name}</b><small>{x.category||"Fornecedor"} · {x.status||"Sem status"}{x.phone?" · "+x.phone:""}</small></>;if(resource==="team")return <><b>{x.name}</b><small>{x.role||"Equipe"}{x.phone?" · "+x.phone:""}</small></>;if(resource==="guests")return <><b>{x.name}</b><small>{x.status==="confirmed"?"Confirmado":x.status==="declined"?"Recusou":x.status==="maybe"?"Talvez":"Pendente"} · +{x.plus_ones||0}</small></>;if(resource==="files")return <><b>{x.name}</b><small>{x.category||"Arquivo"} · {x.mime_type||"tipo não informado"}</small></>;if(resource==="messages")return <><b>{x.author_name||"Equipe Principado"}</b><small>{x.body}</small></>;return <><b>{x.action}</b><small>{x.actor_name||"Sistema"} · {new Date(x.created_at).toLocaleString("pt-BR")}</small></>};
 return <section className="adminClientModule"><div className="adminClientTop"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div><div className="workspaceToolbar"><label>PROJETO<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Todos</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{resource!=="activity"&&<button className="adminPrimaryButton workspaceNew" onClick={()=>{setEditing(null);setForm(initial);setShowForm(true)}}><Plus size={14}/> Novo</button>}</div></div>
 {error&&<div className="adminFormError workspaceError">{error}</div>}
 <div className="workspaceStats"><div><span>REGISTROS</span><b>{items.length}</b></div><div><span>PROJETO</span><b>{projectName}</b></div><div><span>STATUS</span><b>{loading?"Atualizando":"Operacional"}</b></div></div>
 <div className="adminClientGrid workspaceGrid">{showForm&&resource!=="activity"&&<form className="adminPanel adminClientForm" onSubmit={save}><div className="adminPanelHead"><div><span className="eyebrow">{editing?"EDIÇÃO":"NOVO REGISTRO"}</span><h3>{editing?"Atualizar":"Cadastrar"}</h3></div><Check size={16}/></div><div className="adminFormBody">{renderForm()}<button className="adminPrimaryButton" disabled={saving}>{saving?"Salvando...":editing?"Salvar alterações":"Criar registro"}<Plus size={14}/></button><button type="button" className="adminSecondaryButton" onClick={reset}>Cancelar</button></div></form>}
 <div className="adminPanel adminClientList workspaceList"><div className="adminPanelHead"><div><span className="eyebrow">OPERAÇÃO REAL</span><h3>{resource==="activity"?"Histórico de auditoria":title}</h3></div><div className="adminSearch"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar"/></div></div><div className="clientRows">{loading?<div className="adminEmptyRow">Carregando dados...</div>:filtered.length?filtered.map(x=><div className="clientRow workspaceRow" key={x.id}><div className="clientAvatar">{resource==="tasks"?<Check size={13}/>:resource==="activity"?<RefreshCw size={13}/>:<span>{String(x.name||x.title||x.description||x.action||"•").charAt(0).toUpperCase()}</span>}</div><div className="clientMain">{renderItem(x)}</div>{resource!=="activity"&&<div className="projectActions"><button onClick={()=>edit(x)} title="Editar"><Edit3 size={12}/></button><button onClick={()=>remove(x.id)} title="Excluir"><Trash2 size={12}/></button>{resource==="files"&&x.storage_key&&<a href={x.storage_key} target="_blank" rel="noreferrer" title="Abrir"><ExternalLink size={12}/></a>}</div>}</div>):<div className="adminEmptyRow">{projects.length?"Nenhum registro para este projeto.":"Crie um projeto primeiro na aba Projetos."}</div>}</div></div></div></section>
}
