"use client";
import {useEffect,useState} from "react";
import {useClerk,useAuth,RedirectToSignIn} from "@clerk/nextjs";
import {Activity,ArrowUpRight,BarChart3,Bell,Building2,CalendarDays,CheckSquare,ChevronRight,ClipboardList,DollarSign,FileText,FolderOpen,LayoutDashboard,LogOut,Menu,Settings,ShieldCheck,Users,X} from "lucide-react";

type Summary={clients:number;active_projects:number;upcoming_events:number;pending_tasks:number;approved_budget:string|number;confirmed_guests:number};
type Project={id:string;name:string;event_type:string|null;status:string;event_date:string|null;city:string|null;venue:string|null;progress:number;guest_target:number;guest_confirmed:number};
type ActivityItem={id:string;action:string;created_at:string};
const logo="https://principadoproducoes.vercel.app/assets/logo-principado-exact.svg";
const nav=[["Visão geral",LayoutDashboard],["Clientes",Users],["Projetos",FolderOpen],["Produção",ClipboardList],["Orçamento",DollarSign],["Fornecedores",Building2],["Equipe",Users],["Convidados",Users],["Cronograma",CalendarDays],["Arquivos",FileText],["Comunicação",Bell],["Atividade",Activity]] as const;
function money(v:string|number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(v)||0)}
function date(v:string|null){if(!v)return "A definir";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v+"T12:00:00")).replace(".","").toUpperCase()}
export default function AdminPage(){
 const {isLoaded,isSignedIn}=useAuth(); const {signOut}=useClerk(); const [mobile,setMobile]=useState(false); const [active,setActive]=useState("Visão geral");
 const [data,setData]=useState<{summary:Summary;upcoming:Project[];recent:ActivityItem[];user:{display_name:string|null;email:string|null;role:string}}|null>(null); const [error,setError]=useState<string|null>(null);
 useEffect(()=>{if(!isSignedIn)return;fetch("/api/admin/overview",{cache:"no-store"}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error||"Acesso não autorizado.");setData(body)}).catch(e=>setError(e.message))},[isSignedIn]);
 if(!isLoaded)return null; if(!isSignedIn)return <RedirectToSignIn />;
 if(error)return <main className="adminShell"><section className="adminContent"><div className="adminEmpty"><span className="eyebrow">ACESSO RESTRITO</span><h1>Área administrativa</h1><p>{error}</p><a href="/">Voltar ao dashboard</a></div></section></main>;
 if(!data)return <main className="adminShell"><section className="adminContent"><div className="adminEmpty"><span className="eyebrow">CENTRAL DA PRINCIPADO</span><h1>Carregando painel geral.</h1><p>Conectando aos dados administrativos.</p></div></section></main>;
 return <main className="adminShell">
  <aside className={mobile?"adminSidebar open":"adminSidebar"}><div className="adminBrand"><a className="adminLogo" href="https://principadoproducoes.vercel.app"><img src={logo} alt="Principado Produções"/></a><div><b>PRINCIPADO</b><small>CENTRAL DE PRODUÇÃO</small></div><button className="adminClose" onClick={()=>setMobile(false)}><X size={18}/></button></div>
   <div className="ownerBadge"><ShieldCheck size={15}/><div><b>{data.user.display_name||"Proprietário"}</b><small>OWNER · ACESSO TOTAL</small></div></div>
   <nav className="adminNav">{nav.map(([name,Icon])=><button key={name} className={active===name?"active":""} onClick={()=>{setActive(name);setMobile(false)}}><Icon size={16}/>{name}</button>)}</nav>
   <div className="adminBottom"><a href="https://principadoproducoes.vercel.app"><ArrowUpRight size={14}/> Site Principado</a><button onClick={()=>signOut({redirectUrl:"/login"})}><LogOut size={14}/> Sair da conta</button></div>
  </aside>
  <section className="adminContent"><header className="adminHeader"><div><button className="adminMenu" onClick={()=>setMobile(true)}><Menu/></button><span className="eyebrow">PAINEL GERAL · {data.user.role.toUpperCase()}</span><h1>{active}</h1><p>Visão completa da operação, projetos e produção da Principado.</p></div><div className="adminHeaderRight"><span className="liveDot"/> SISTEMA ONLINE</div></header>
   {active==="Visão geral"?<>
    <section className="adminHero"><div><span className="eyebrow">CENTRAL DA PRINCIPADO</span><h2>Produção sob controle.</h2><p>Todos os projetos, clientes, etapas e números operacionais em um único lugar.</p></div><div className="adminHeroMark"><BarChart3 size={30}/></div></section>
    <section className="adminStats"><article><span>Clientes</span><strong>{data.summary.clients}</strong><small>Cadastros ativos na base</small></article><article><span>Projetos em andamento</span><strong>{data.summary.active_projects}</strong><small>Produções não encerradas</small></article><article><span>Próximos eventos</span><strong>{data.summary.upcoming_events}</strong><small>Eventos a partir de hoje</small></article><article><span>Pendências</span><strong>{data.summary.pending_tasks}</strong><small>Tarefas aguardando ação</small></article><article><span>Orçamento aprovado</span><strong>{money(data.summary.approved_budget)}</strong><small>Projetos não cancelados</small></article><article><span>Convidados confirmados</span><strong>{data.summary.confirmed_guests}</strong><small>Total consolidado</small></article></section>
    <section className="adminGrid"><div className="adminPanel adminWide"><div className="adminPanelHead"><div><span className="eyebrow">AGENDA OPERACIONAL</span><h3>Próximos projetos</h3></div><button>Ver todos <ArrowUpRight size={14}/></button></div><div className="adminRows">{data.upcoming.length?data.upcoming.map(p=><div className="adminRow" key={p.id}><div className="dateBox"><b>{p.event_date?new Date(p.event_date+"T12:00:00").getDate():"—"}</b><small>{p.event_date?new Intl.DateTimeFormat("pt-BR",{month:"short"}).format(new Date(p.event_date+"T12:00:00")).replace(".","").toUpperCase():"A DEFINIR"}</small></div><div className="rowMain"><b>{p.name}</b><small>{p.event_type||"Evento"} · {p.city||"Cidade a definir"}{p.venue?" · "+p.venue:""}</small></div><div className="rowProgress"><span>{p.progress}%</span><i><em style={{width:p.progress+"%"}}/></i></div><ChevronRight size={16}/></div>):<div className="adminEmptyRow">Nenhum projeto cadastrado ainda.</div>}</div></div>
     <div className="adminPanel"><div className="adminPanelHead"><div><span className="eyebrow">SEGURANÇA</span><h3>Acesso administrativo</h3></div></div><div className="securityList"><div><ShieldCheck/><span><b>Seu perfil</b><small>OWNER · acesso total</small></span></div><div><Settings/><span><b>Permissões</b><small>Controle por função e projeto</small></span></div><div><CheckSquare/><span><b>Proteção</b><small>Autorização aplicada no servidor</small></span></div></div></div></section>
    <section className="adminPanel"><div className="adminPanelHead"><div><span className="eyebrow">AUDITORIA</span><h3>Atividade recente</h3></div><button>Histórico completo <ArrowUpRight size={14}/></button></div><div className="activityList">{data.recent.length?data.recent.map(a=><div key={a.id}><Activity size={14}/><span><b>{a.action}</b><small>{new Date(a.created_at).toLocaleString("pt-BR")}</small></span></div>):<div className="adminEmptyRow">Nenhuma atividade registrada ainda.</div>}</div></section>
   </>:<section className="adminPanel adminModule"><span className="eyebrow">GESTÃO</span><h2>{active}</h2><p>Este módulo está reservado à operação interna. A estrutura visual e as permissões já estão preparadas; os próximos módulos serão conectados às tabelas e fluxos reais da produção.</p><div className="moduleCards"><div><ShieldCheck/><b>Acesso protegido</b><small>Somente perfis administrativos podem acessar esta área.</small></div><div><ClipboardList/><b>Dados por projeto</b><small>Clientes, produção, orçamento e equipe ficam separados por evento.</small></div><div><Activity/><b>Rastreabilidade</b><small>As ações administrativas serão registradas no histórico.</small></div></div></section>}
   <footer className="adminFooter"><span>PRINCIPADO PRODUÇÕES</span><span>PAINEL GERAL · {data.user.role.toUpperCase()}</span></footer>
  </section>
 </main>
}
