"use client";
import { useState } from "react";
import { Plus, Search } from "lucide-react";

type Client={id:string;name:string;company_name:string|null};
type Project={id:string;name:string;event_type:string|null;status:string;event_date:string|null;event_time:string|null;city:string|null;venue:string|null;description:string|null;budget_planned:string|number;budget_approved:string|number;guest_target:number;guest_confirmed:number;progress:number;client_id:string|null;client_name:string|null;client_company:string|null;task_count:number;completed_task_count:number};

const empty={name:"",event_type:"",status:"planning",event_date:"",event_time:"",city:"",venue:"",description:"",client_id:"",budget_planned:"",budget_approved:"",guest_target:"",progress:"0"};

export default function ProjectsModule({projects,clients,onSaved}:{projects:Project[];clients:Client[];onSaved:(p:Project,deleted?:string)=>void}){
 const [form,setForm]=useState<any>(empty),[editing,setEditing]=useState<string|null>(null),[query,setQuery]=useState(""),[saving,setSaving]=useState(false),[error,setError]=useState<string|null>(null);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError(null);if(!form.name.trim()){setError("Informe o nome do projeto.");return}setSaving(true);try{const r=await fetch("/api/admin/projects",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id:editing,budget_planned:Number(form.budget_planned)||0,budget_approved:Number(form.budget_approved)||0,guest_target:Number(form.guest_target)||0,progress:Number(form.progress)||0})});const b=await r.json();if(!r.ok)throw new Error(b.error||"Não foi possível salvar.");const client=clients.find(c=>c.id===b.project.client_id);onSaved({...b.project,client_name:client?.name||null,client_company:client?.company_name||null,task_count:editing?projects.find(p=>p.id===editing)?.task_count||0:0,completed_task_count:editing?projects.find(p=>p.id===editing)?.completed_task_count||0:0});setForm(empty);setEditing(null)}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar projeto")}finally{setSaving(false)}};
 const edit=(p:Project)=>{setEditing(p.id);setForm({name:p.name,event_type:p.event_type||"",status:p.status,event_date:p.event_date||"",event_time:p.event_time||"",city:p.city||"",venue:p.venue||"",description:p.description||"",client_id:p.client_id||"",budget_planned:p.budget_planned||"",budget_approved:p.budget_approved||"",guest_target:p.guest_target||"",progress:p.progress||0})};
 const remove=async(id:string)=>{if(!window.confirm("Excluir este projeto? Essa ação não pode ser desfeita."))return;const r=await fetch("/api/admin/projects",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const b=await r.json();if(!r.ok){setError(b.error||"Não foi possível excluir.");return}onSaved({id} as Project,id);if(editing===id){setEditing(null);setForm(empty)}};
 const filtered=projects.filter(p=>[p.name,p.event_type||"",p.city||"",p.venue||"",p.client_name||"",p.client_company||""].join(" ").toLowerCase().includes(query.toLowerCase()));
 const field=(label:string,key:string,props:any={})=><label>{label}<input {...props} value={form[key]} onChange={e=>setForm((v:any)=>({...v,[key]:e.target.value}))}/></label>;
 return <section className="adminClientModule"><div className="adminClientTop"><div><span className="eyebrow">OPERAÇÃO</span><h2>Projetos</h2><p>Controle central de cada produção, do briefing ao evento.</p></div><div className="adminClientCount"><b>{projects.length}</b><small>PROJETOS</small></div></div><div className="adminClientGrid">
 <form className="adminPanel adminClientForm" onSubmit={save}><div className="adminPanelHead"><div><span className="eyebrow">{editing?"EDITAR PROJETO":"NOVO PROJETO"}</span><h3>{editing?"Atualizar produção":"Criar projeto"}</h3></div><Plus size={17}/></div><div className="adminFormBody">
 {field("Nome do projeto *","name",{placeholder:"Ex.: Evento corporativo 2026"})}<label>Cliente<select value={form.client_id} onChange={e=>setForm((v:any)=>({...v,client_id:e.target.value}))}><option value="">Selecionar cliente</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}{c.company_name?" · "+c.company_name:""}</option>)}</select></label>
 {field("Tipo de evento","event_type",{placeholder:"Corporativo, social..."})}<div className="adminFormTwo">{field("Data","event_date",{type:"date"})}{field("Horário","event_time",{type:"time"})}</div><div className="adminFormTwo">{field("Cidade","city")}{field("Local","venue")}</div>
 <div className="adminFormTwo"><label>Status<select value={form.status} onChange={e=>setForm((v:any)=>({...v,status:e.target.value}))}><option value="planning">Planejamento</option><option value="production">Produção</option><option value="event_day">Dia do evento</option><option value="completed">Concluído</option><option value="cancelled">Cancelado</option></select></label>{field("Progresso %","progress",{type:"number",min:0,max:100})}</div>
 <div className="adminFormTwo">{field("Orçamento planejado","budget_planned",{type:"number",min:0,step:"0.01"})}{field("Orçamento aprovado","budget_approved",{type:"number",min:0,step:"0.01"})}</div>{field("Meta de convidados","guest_target",{type:"number",min:0})}<label>Descrição<textarea value={form.description} onChange={e=>setForm((v:any)=>({...v,description:e.target.value}))} placeholder="Briefing e observações principais"/></label>
 {error&&<p className="adminFormError">{error}</p>}<button className="adminPrimaryButton" disabled={saving}>{saving?"Salvando...":editing?"Atualizar projeto":"Criar projeto"}<Plus size={14}/></button>{editing&&<button type="button" className="adminSecondaryButton" onClick={()=>{setEditing(null);setForm(empty)}}>Cancelar edição</button>}</div></form>
 <div className="adminPanel adminClientList"><div className="adminPanelHead"><div><span className="eyebrow">PORTFÓLIO OPERACIONAL</span><h3>Projetos cadastrados</h3></div><div className="adminSearch"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar projeto"/></div></div><div className="clientRows">{filtered.length?filtered.map(p=><div className="clientRow" key={p.id}><div className="clientAvatar">{p.name.charAt(0).toUpperCase()}</div><div className="clientMain"><b>{p.name}</b><small>{p.client_name||"Cliente a definir"} · {p.event_type||"Evento"} · {p.city||"Cidade a definir"}</small></div><div className="clientMeta"><b>{p.progress}%</b><small>{p.completed_task_count}/{p.task_count} tarefas</small></div><div className="projectActions"><button type="button" onClick={()=>edit(p)}>Editar</button><button type="button" onClick={()=>remove(p.id)}>Excluir</button></div></div>):<div className="adminEmptyRow">{projects.length?"Nenhum projeto encontrado.":"Nenhum projeto cadastrado ainda."}</div>}</div></div></div></section>
}