"use client";
import {useEffect,useMemo,useState} from "react";
import {RedirectToSignIn,useAuth,useClerk} from "@clerk/nextjs";
import {CalendarDays,CheckCircle2,ClipboardCheck,Clock3,FileText,FolderOpen,LayoutDashboard,MessageSquare,Users,WalletCards,Building2,ArrowUpRight,Menu,X,PlayCircle,LogOut,ExternalLink} from "lucide-react";

type Task={id:string;title:string;done:boolean;tag:string;due_date:string|null};
type Project={id:string;name:string;event_type:string|null;status:string;event_date:string|null;event_time:string|null;city:string|null;venue:string|null;description:string|null;budget_planned:string|number;budget_approved:string|number;guest_target:number;guest_confirmed:number;progress:number;tasks:Task[]};
const logo="https://principadoproducoes.vercel.app/assets/logo-principado-exact.svg";
const nav=[["Visão geral",LayoutDashboard],["Briefing",FileText],["Cronograma",CalendarDays],["Checklist",ClipboardCheck],["Orçamento",WalletCards],["Fornecedores",Building2],["Equipe",Users],["Convidados",Users],["Roteiro",PlayCircle],["Arquivos",FolderOpen],["Comunicação",MessageSquare]] as const;

function formatDate(date:string|null){if(!date)return "Data a definir";return new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(date+"T12:00:00")).replace(" de "," ").replace(".","").toUpperCase();}
function formatMoney(value:string|number){return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(value)||0);}
function daysUntil(date:string|null){if(!date)return null;const a=new Date();a.setHours(0,0,0,0);const b=new Date(date+"T00:00:00");return Math.ceil((b.getTime()-a.getTime())/86400000);}

export default function Home(){
 const {signOut}=useClerk(); const {isLoaded,isSignedIn}=useAuth();
 const [active,setActive]=useState("Visão geral"); const [mobile,setMobile]=useState(false); const [project,setProject]=useState<Project|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);

 useEffect(()=>{if(!isSignedIn)return; fetch("/api/projects",{cache:"no-store"}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error||"Não foi possível carregar o projeto.");setProject(data.projects?.[0]??null);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[isSignedIn]);

 const tasks=useMemo(()=>project?.tasks?.map(t=>({...t,done:t.status==="completed",tag:t.category||"Produção"}))??[],[project]);
 const done=tasks.filter(t=>t.done).length; const progress=project?.progress??(tasks.length?Math.round(done/tasks.length*100):0); const days=daysUntil(project?.event_date??null);
 if(!isLoaded)return null; if(!isSignedIn)return <RedirectToSignIn />;
 if(loading)return <main className="shell"><section className="content"><div className="panel placeholder"><span className="eyebrow">PRINCIPADO DASHBOARD</span><h2>Carregando seu projeto.</h2><p>Estamos buscando os dados vinculados à sua conta.</p></div></section></main>;
 if(error)return <main className="shell"><section className="content"><div className="panel placeholder"><span className="eyebrow">ATENÇÃO</span><h2>Não foi possível carregar o projeto.</h2><p>{error}</p></div></section></main>;
 if(!project)return <main className="shell"><section className="content"><div className="panel placeholder"><span className="eyebrow">ÁREA DO CLIENTE</span><h2>Nenhum projeto vinculado.</h2><p>Sua conta foi autenticada, mas ainda não existe um projeto associado a ela. A equipe Principado poderá vincular seu projeto por aqui.</p><a className="returnSite" href="https://principadoproducoes.vercel.app">Voltar ao site Principado</a></div></section></main>;

 return (<main className="shell">
  <aside className={mobile?"sidebar open":"sidebar"}>
   <div className="brand"><a className="brandLogo" href="https://principadoproducoes.vercel.app" aria-label="Principado Produções"><img src={logo} alt="Principado Produções"/></a><div className="brandText"><b>PRINCIPADO</b><small>PRODUÇÕES · DASHBOARD</small></div><button className="close" onClick={()=>setMobile(false)}><X size={18}/></button></div>
   <div className="project"><span>PROJETO ATIVO</span><strong>{project.name}</strong><small>{formatDate(project.event_date)} · {project.city||"LOCAL A DEFINIR"}</small></div>
   <nav>{nav.map(([label,Icon])=><button key={label} className={active===label?"active":""} onClick={()=>{setActive(label);setMobile(false)}}><Icon size={17}/>{label}</button>)}</nav>
   <div className="sidebarBottom"><div className="client"><span>PP</span><div><b>Cliente</b><small>{project.event_type||"Projeto Principado"}</small></div></div><a className="backSite" href="https://principadoproducoes.vercel.app"><ExternalLink size={14}/> Site Principado</a><button className="logout" onClick={()=>signOut({redirectUrl:"/login"})}><LogOut size={14}/> Sair da conta</button></div>
  </aside>
  <section className="content">
   <header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><span className="eyebrow">CENTRAL DO CLIENTE</span><h1>{active}</h1><p>Tenha visão, controle e organização de cada etapa da produção.</p></div><button className="profile">PP</button></header>
   {active==="Visão geral"?<><div className="hero"><div><span className="eyebrow">PRÓXIMO MARCO</span><h2>{project.name}</h2><p>{formatDate(project.event_date)} · {project.event_time?.slice(0,5)||"Horário a definir"} · {project.city||"Cidade a definir"}</p><div className="heroMeta"><span><Clock3 size={16}/> {days===null?"Data a definir":days<0?"Evento realizado":days===0?"É hoje":days+" dias para o evento"}</span><span><CheckCircle2 size={16}/> {progress}% concluído</span></div></div><div className="heroAction"><button onClick={()=>setActive("Cronograma")}>Ver cronograma <ArrowUpRight size={17}/></button></div></div>
   <div className="stats"><article><span>Progresso geral</span><strong>{progress}%</strong><div className="bar"><i style={{width:progress+"%"}}/></div></article><article><span>Entregas pendentes</span><strong>{tasks.length-done}</strong><small>Itens que exigem atenção</small></article><article><span>Orçamento aprovado</span><strong>{formatMoney(project.budget_approved)}</strong><small>de {formatMoney(project.budget_planned)} previstos</small></article><article><span>Convidados</span><strong>{project.guest_confirmed}</strong><small>de {project.guest_target} previstos</small></article></div>
   <div className="grid"><section className="panel wide"><div className="panelHead"><div><span className="eyebrow">ACOMPANHAMENTO</span><h3>Próximas entregas</h3></div><button className="ghost">Ver tudo <ArrowUpRight size={15}/></button></div><div className="tasks">{tasks.slice(0,6).map(task=><label className="task" key={task.id}><input type="checkbox" checked={task.done} readOnly/><span className="fakeCheck">{task.done?"✓":""}</span><div><b className={task.done?"done":""}>{task.title}</b><small>{task.tag}</small></div><span className="taskDate">{task.done?"Concluído":task.due_date?formatDate(task.due_date):"Pendente"}</span></label>)}{tasks.length===0&&<div className="task"><div><b>Nenhuma entrega cadastrada</b><small>As tarefas do projeto aparecerão aqui.</small></div></div>}</div></section><section className="panel"><div className="panelHead"><div><span className="eyebrow">PROJETO</span><h3>Dados principais</h3></div></div><div className="timeline"><div><span>STATUS</span><b>{project.status.replace("_"," ").toUpperCase()}</b><small>{project.description||"Projeto em produção pela Principado."}</small></div><div><span>LOCAL</span><b>{project.venue||"Local a definir"}</b><small>{project.city||"Cidade a definir"}</small></div><div><span>CONVIDADOS</span><b>{project.guest_confirmed} confirmados</b><small>Meta: {project.guest_target}</small></div><div><span>EVENTO</span><b>{formatDate(project.event_date)}</b><small>{project.event_time?.slice(0,5)||"Horário a definir"}</small></div></div></section></div></>:<section className="panel placeholder"><span className="eyebrow">MÓDULO</span><h2>{active}</h2><p>Este módulo já está previsto na estrutura do Principado Dashboard. A próxima etapa é conectar seus dados reais, permissões e colaboração com a equipe Principado.</p><div className="placeholderCards"><div><CheckCircle2/><b>Organização</b><small>Dados estruturados por projeto.</small></div><div><Users/><b>Colaboração</b><small>Cliente e produção no mesmo fluxo.</small></div><div><FolderOpen/><b>Histórico</b><small>Arquivos, decisões e entregas centralizados.</small></div></div></section>}
   <footer><span>PRINCIPADO PRODUÇÕES</span><span>Dashboard do cliente · {project.name}</span></footer>
  </section>
 </main>);
}
